/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Clases.*;
import javax.swing.JOptionPane;

/**
 *
 * @author raulpenate
 */
public class panelMostrarEdificio extends javax.swing.JFrame {

    ArrayList<EdificioLaEmpresa> lEdificioLaEmpresas = new ArrayList<>();
    //TABLAS
    DefaultTableModel mdDatosGenerales = new DefaultTableModel();
    DefaultTableModel mdAreaInterna = new DefaultTableModel();
    DefaultTableModel mdAreaExterna = new DefaultTableModel();

    ;
    public void cargarTablas() {
        //UNO
        String[] columTblUno = {"Nombre Edificio", "Ubicación", "Cantidad de Plantas", "Tipo"};
        for (int i = 0; i < columTblUno.length; i++) {
            mdDatosGenerales.addColumn(columTblUno[i]);
        }
        tblDatosGenerales.setModel(mdDatosGenerales);
        //DOS
        String[] columTblDos = {"Cant. Cuartos", "Cant. Sala Reuniones", "Comedor", "Cant. Baños", "Área Emergencias"};
        for (int i = 0; i < columTblDos.length; i++) {
            mdAreaInterna.addColumn(columTblDos[i]);
        }
        tblaAreaInterna.setModel(mdAreaInterna);
        //Tres
        String[] columTblTres = {"Parque", "Patio Trasero", "Torre Vigilancia", "Calles Internas", "Canchas"};
        for (int i = 0; i < columTblTres.length; i++) {
            mdAreaExterna.addColumn(columTblTres[i]);
        }
        jTable2.setModel(mdAreaExterna);
        //CB UBICAICON
        String[] elementosCbUbicacion = {"Ahuchapan", "Santa Ana", "San Salvador", "Usulutan", "San Miguel", "Morazan", "Chalatenango"};
        for (int i = 0; i < elementosCbUbicacion.length; i++) {
            cbUbicacion.addItem(elementosCbUbicacion[i]);
        }
        //CB TIPO
        String[] elementosCbTipo = {"Polideportivo", "Hospitalario", "Educativo"};
        for (int i = 0; i < elementosCbTipo.length; i++) {
            cbTipo.addItem(elementosCbTipo[i]);
        }
    }

    /**
     * Creates new form panelMostrarEdificio
     */
    public panelMostrarEdificio() {
        initComponents();
        cargarTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comedor = new javax.swing.ButtonGroup();
        parque = new javax.swing.ButtonGroup();
        torreVigilancia = new javax.swing.ButtonGroup();
        CallesInternas = new javax.swing.ButtonGroup();
        canchas = new javax.swing.ButtonGroup();
        patio = new javax.swing.ButtonGroup();
        AreaEmergencias = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cbUbicacion = new javax.swing.JComboBox<>();
        spCantidadPlantas = new javax.swing.JSpinner();
        cbTipo = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        spCantidadBaños = new javax.swing.JSpinner();
        rbComedorSi = new javax.swing.JRadioButton();
        rbComedorNo = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        rbAreaEmergenciasSi = new javax.swing.JRadioButton();
        rbAreaEmergenciasNo = new javax.swing.JRadioButton();
        spCantidadSalaReuniones = new javax.swing.JSpinner();
        spCantidadCuartos = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        rbParqueSi = new javax.swing.JRadioButton();
        rbParqueNo = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        rbPatioTraseroSi = new javax.swing.JRadioButton();
        rbPatioTraseroNo = new javax.swing.JRadioButton();
        rbTorreVigilanciaSi = new javax.swing.JRadioButton();
        rbTorreVigilanciaNo = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        rbCallesInternasNo = new javax.swing.JRadioButton();
        rbCallesInternasSi = new javax.swing.JRadioButton();
        rbCanchasNo = new javax.swing.JRadioButton();
        rbCanchasSi = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosGenerales = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblaAreaInterna = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Edificio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Nombre Edificio");

        jLabel6.setText("Ubicación");

        jLabel7.setText("Cantidad de Plantas");

        jLabel8.setText("Tipo");

        cbUbicacion.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        spCantidadPlantas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 2));

        cbTipo.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spCantidadPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spCantidadPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setText("Cantidad de Cuartos");

        jLabel10.setText("Cant. Salas de Reunión");

        jLabel11.setText("Comedor");

        jLabel12.setText("Cantidad de Baños");

        spCantidadBaños.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        comedor.add(rbComedorSi);
        rbComedorSi.setSelected(true);
        rbComedorSi.setText("Sí");

        comedor.add(rbComedorNo);
        rbComedorNo.setText("No");

        jLabel13.setText("Area Emergencias");

        AreaEmergencias.add(rbAreaEmergenciasSi);
        rbAreaEmergenciasSi.setText("Sí");

        AreaEmergencias.add(rbAreaEmergenciasNo);
        rbAreaEmergenciasNo.setSelected(true);
        rbAreaEmergenciasNo.setText("No");

        spCantidadSalaReuniones.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 5));

        spCantidadCuartos.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 5));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(spCantidadBaños, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rbComedorSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbComedorNo))
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rbAreaEmergenciasSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbAreaEmergenciasNo))
                    .addComponent(spCantidadSalaReuniones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spCantidadCuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spCantidadCuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spCantidadSalaReuniones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbComedorNo)
                    .addComponent(rbComedorSi))
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spCantidadBaños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAreaEmergenciasSi)
                    .addComponent(rbAreaEmergenciasNo))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Interna", jPanel5);

        jLabel17.setText("Parque");

        parque.add(rbParqueSi);
        rbParqueSi.setText("Sí");

        parque.add(rbParqueNo);
        rbParqueNo.setSelected(true);
        rbParqueNo.setText("No");

        jLabel18.setText("Patio Trasero");

        patio.add(rbPatioTraseroSi);
        rbPatioTraseroSi.setText("Sí");

        patio.add(rbPatioTraseroNo);
        rbPatioTraseroNo.setSelected(true);
        rbPatioTraseroNo.setText("No");

        torreVigilancia.add(rbTorreVigilanciaSi);
        rbTorreVigilanciaSi.setText("Sí");

        torreVigilancia.add(rbTorreVigilanciaNo);
        rbTorreVigilanciaNo.setSelected(true);
        rbTorreVigilanciaNo.setText("No");

        jLabel19.setText("Torre VIgilancia");

        jLabel20.setText("Calles Internas");

        CallesInternas.add(rbCallesInternasNo);
        rbCallesInternasNo.setSelected(true);
        rbCallesInternasNo.setText("No");

        CallesInternas.add(rbCallesInternasSi);
        rbCallesInternasSi.setText("Sí");

        canchas.add(rbCanchasNo);
        rbCanchasNo.setSelected(true);
        rbCanchasNo.setText("No");

        canchas.add(rbCanchasSi);
        rbCanchasSi.setText("Sí");

        jLabel21.setText("Canchas");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(rbPatioTraseroSi)
                                .addGap(8, 8, 8)
                                .addComponent(rbPatioTraseroNo)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(rbParqueSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbParqueNo))))
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(rbCanchasSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbCanchasNo))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(rbCallesInternasSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbCallesInternasNo))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(rbTorreVigilanciaSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbTorreVigilanciaNo)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbParqueSi)
                    .addComponent(rbParqueNo))
                .addGap(13, 13, 13)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbPatioTraseroNo)
                    .addComponent(rbPatioTraseroSi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTorreVigilanciaSi)
                    .addComponent(rbTorreVigilanciaNo))
                .addGap(12, 12, 12)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCallesInternasSi)
                    .addComponent(rbCallesInternasNo))
                .addGap(12, 12, 12)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCanchasNo)
                    .addComponent(rbCanchasSi))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Externa", jPanel6);

        btnMostrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMostrar.setText("AGREGAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mostrar Edificios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Generales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        tblDatosGenerales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosGeneralesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatosGenerales);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Área Interna"));
        jPanel10.setPreferredSize(new java.awt.Dimension(10, 90));

        tblaAreaInterna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblaAreaInterna);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Área Externa"));
        jPanel12.setPreferredSize(new java.awt.Dimension(10, 90));

        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        try {
            //Verifica que nombre no sea vacio
            if (!txtNombre.getText().equals("")) {
                //Verificar los booleanos
                lEdificioLaEmpresas.add(new EdificioLaEmpresa(
                        txtNombre.getText(),
                        cbUbicacion.getSelectedItem() + "",
                        spCantidadPlantas.getValue().hashCode(),
                        cbTipo.getSelectedItem() + "",
                        spCantidadCuartos.getValue().hashCode(),
                        spCantidadSalaReuniones.getValue().hashCode(),
                        rbComedorSi.isSelected(),
                        spCantidadBaños.getValue().hashCode(),
                        rbAreaEmergenciasSi.isSelected(),
                        rbParqueSi.isSelected(),
                        rbPatioTraseroSi.isSelected(),
                        rbTorreVigilanciaSi.isSelected(),
                        rbCallesInternasSi.isSelected(),
                        rbCanchasSi.isSelected()
                ));
                //Limpiar tabla
                mdDatosGenerales.setRowCount(0);
                //Imprimir en tabla
                for (int i = 0; i < lEdificioLaEmpresas.size(); i++) {
                    String[] rowDatosPrincipales = {
                        lEdificioLaEmpresas.get(i).getNombre().trim().toUpperCase(),
                        lEdificioLaEmpresas.get(i).getUbicacion(),
                        lEdificioLaEmpresas.get(i).getCantidad_de_plantas() + "",
                        lEdificioLaEmpresas.get(i).geTipo()
                    };
                    mdDatosGenerales.addRow(rowDatosPrincipales);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese un nombre para el edificio, seleccione bien que tipo será y equipelo correctamente.");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void tblDatosGeneralesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosGeneralesMouseClicked
        mdAreaInterna.setRowCount(0);
        mdAreaExterna.setRowCount(0);
        //VER QUE LINEA SELECIONO
        int index = tblDatosGenerales.getSelectedRow();
        //Cambiar datos a SI
        String comedor = lEdificioLaEmpresas.get(index).comedor() == true ? "Si" : "No";
        String areaDeEmergencia = lEdificioLaEmpresas.get(index).areaDeEmergencias() == true ? "Si" : "No";
        // SE IMPRIMEN LOS DATOS
        String[] rowAreaInterna = {
            lEdificioLaEmpresas.get(index).getCantidad_cuartos() + "",
            lEdificioLaEmpresas.get(index).cantidadSalonesDeReuniones() + "",
            comedor,
            lEdificioLaEmpresas.get(index).cantidadBaños() + "",
            areaDeEmergencia};
        mdAreaInterna.addRow(rowAreaInterna);
        //Cambiar datos a SI
        String parque = lEdificioLaEmpresas.get(index).parqueo() == true ? "Si" : "No";
        String patrio_trasero = lEdificioLaEmpresas.get(index).patioTrasero() == true ? "Si" : "No";
        String torreVigilancia = lEdificioLaEmpresas.get(index).torreVigiliancia() == true ? "Si" : "No";
        String calle_interna = lEdificioLaEmpresas.get(index).callesInternas() == true ? "Si" : "No";
        String canchas = lEdificioLaEmpresas.get(index).patioTrasero() == true ? "Si" : "No";
        // SE IMPRIMEN LOS DATOS
        String[] rowAreaExterna = {
            parque,
            patrio_trasero,
            torreVigilancia,
            calle_interna,
            canchas};
        mdAreaExterna.addRow(rowAreaExterna);
    }//GEN-LAST:event_tblDatosGeneralesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelMostrarEdificio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelMostrarEdificio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelMostrarEdificio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelMostrarEdificio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelMostrarEdificio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AreaEmergencias;
    private javax.swing.ButtonGroup CallesInternas;
    private javax.swing.JButton btnMostrar;
    private javax.swing.ButtonGroup canchas;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JComboBox<String> cbUbicacion;
    private javax.swing.ButtonGroup comedor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.ButtonGroup parque;
    private javax.swing.ButtonGroup patio;
    private javax.swing.JRadioButton rbAreaEmergenciasNo;
    private javax.swing.JRadioButton rbAreaEmergenciasSi;
    private javax.swing.JRadioButton rbCallesInternasNo;
    private javax.swing.JRadioButton rbCallesInternasSi;
    private javax.swing.JRadioButton rbCanchasNo;
    private javax.swing.JRadioButton rbCanchasSi;
    private javax.swing.JRadioButton rbComedorNo;
    private javax.swing.JRadioButton rbComedorSi;
    private javax.swing.JRadioButton rbParqueNo;
    private javax.swing.JRadioButton rbParqueSi;
    private javax.swing.JRadioButton rbPatioTraseroNo;
    private javax.swing.JRadioButton rbPatioTraseroSi;
    private javax.swing.JRadioButton rbTorreVigilanciaNo;
    private javax.swing.JRadioButton rbTorreVigilanciaSi;
    private javax.swing.JSpinner spCantidadBaños;
    private javax.swing.JSpinner spCantidadCuartos;
    private javax.swing.JSpinner spCantidadPlantas;
    private javax.swing.JSpinner spCantidadSalaReuniones;
    private javax.swing.JTable tblDatosGenerales;
    private javax.swing.JTable tblaAreaInterna;
    private javax.swing.ButtonGroup torreVigilancia;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
